module.exports = {
    trackers: [
        'google-analytics.com',
        'googletagmanager.com',
        'googleadservices.com',
        'connect.facebook.net',
        'facebook.com/tr',
        'hotjar.com',
        'mixpanel.com',
        'segment.io',
        'amplitude.com',
        'heap.io',
        'mouseflow.com',
        'crazyegg.com',
        'optimizely.com',
        'fullstory.com',
        'sentry.io',
        'newrelic.com',
        'branch.io',
        'adjust.com',
        'appsflyer.com',
        'branch.io'
    ],
    ads: [
        'doubleclick.net',
        'adservice.google.com',
        'adnxs.com',
        'ads.yahoo.com',
        'advertising.com',
        'demdex.net',
        'amazon-adsystem.com',
        'media.net',
        'propellerads.com',
        'popads.net',
        'monetag.com',
        'adsterra.com',
        'clickadu.com',
        'exo.com',
        'revcontent.com',
        'outbrain.com',
        'taboola.com',
        'criteo.com',
        'quantserve.com',
        'scorecardresearch.com'
    ],
    suspiciousTLDs: ['.zip', '.mov', '.top', '.click', '.xyz', '.buzz', '.tk', '.ml', '.ga', '.cf']
};
